from __future__ import annotations


CRYPTOS = [
    {"coin_id": "bitcoin", "symbol": "BTC", "name": "Bitcoin"},
    {"coin_id": "ethereum", "symbol": "ETH", "name": "Ethereum"},
]


CATEGORIES = [
    {
        "id": "crypto_beta",
        "name": "数字资产高 Beta",
        "description": "受 BTC、稳定币、交易活跃度和加密资本市场周期驱动，弹性高，波动也最大。",
        "benchmark": "BTC",
    },
    {
        "id": "ai_compute",
        "name": "AI / 半导体 / 算力",
        "description": "围绕 GPU、HBM、云与网络基础设施，核心变量是 AI 资本开支和估值消化。",
        "benchmark": "NVDA",
    },
    {
        "id": "growth_platform",
        "name": "平台 / 券商 / 成长服务",
        "description": "商业模式相对成熟，但估值和交易情绪仍有弹性，适合和市场风格一起观察。",
        "benchmark": "META",
    },
    {
        "id": "healthcare_special",
        "name": "医疗成长 / 特殊主题",
        "description": "更依赖单一产品周期、监管进展或主题弹性，研究深度和仓位纪律同等重要。",
        "benchmark": "HIMS",
    },
    {
        "id": "ev_beta",
        "name": "电动车与高弹性工具",
        "description": "对行业销量、价格战、利率和市场风险偏好敏感，仓位控制比观点更重要。",
        "benchmark": "XPEV",
    },
    {
        "id": "hk_internet",
        "name": "港股互联网与指数工具",
        "description": "受政策、消费复苏、平台盈利预期影响，同时带有港股风险偏好特征。",
        "benchmark": "00700.HK",
    },
]


ASSETS = [
    {
        "symbol": "MSTR",
        "quote_code": "mstr.us",
        "market": "US",
        "currency": "USD",
        "name": "Strategy",
        "name_zh": "Strategy",
        "category": "crypto_beta",
        "fundamental_score": 3,
        "risk_level": "高",
        "style": "crypto_beta",
        "business_note": "核心逻辑是 BTC 储备与融资能力，更多是高弹性资产负债表交易。",
        "fundamental_note": "基本面高度依赖 BTC 走势和融资环境，非传统软件估值框架。",
        "watch_items": "BTC 趋势、融资动作、持币变化",
        "news_query": "MSTR OR Strategy bitcoin stock when:7d",
    },
    {
        "symbol": "BMNR",
        "quote_code": "bmnr.us",
        "market": "US",
        "currency": "USD",
        "name": "BitMine Immersion",
        "name_zh": "BitMine Immersion",
        "category": "crypto_beta",
        "fundamental_score": 2,
        "risk_level": "很高",
        "style": "speculative",
        "business_note": "偏挖矿与高波动加密基础设施，通常放大 BTC 周期。",
        "fundamental_note": "盈利稳定性弱，更多依赖景气和叙事驱动。",
        "watch_items": "矿机效率、电价、扩产、BTC",
        "news_query": "BMNR OR BitMine Immersion Technologies stock when:7d",
    },
    {
        "symbol": "COIN",
        "quote_code": "coin.us",
        "market": "US",
        "currency": "USD",
        "name": "Coinbase",
        "name_zh": "Coinbase",
        "category": "crypto_beta",
        "fundamental_score": 4,
        "risk_level": "高",
        "style": "platform",
        "business_note": "交易所、托管与机构业务兼具，是加密行业核心基础设施之一。",
        "fundamental_note": "基本面强于多数加密弹性股，但盈利仍受交易量周期影响。",
        "watch_items": "成交量、监管、稳定币与托管业务",
        "news_query": "COIN OR Coinbase stock crypto when:7d",
    },
    {
        "symbol": "CRCL",
        "quote_code": "crcl.us",
        "market": "US",
        "currency": "USD",
        "name": "Circle Internet Group",
        "name_zh": "Circle",
        "category": "crypto_beta",
        "fundamental_score": 3,
        "risk_level": "高",
        "style": "stablecoin",
        "business_note": "围绕 USDC 和支付基础设施，受监管、利率和链上生态影响。",
        "fundamental_note": "护城河在合规与渠道，但商业模式仍在扩张验证阶段。",
        "watch_items": "USDC 流通量、利率、合规进展、支付合作",
        "news_query": "CRCL OR Circle stock USDC when:7d",
    },
    {
        "symbol": "IREN",
        "quote_code": "iren.us",
        "market": "US",
        "currency": "USD",
        "name": "IREN",
        "name_zh": "IREN",
        "category": "crypto_beta",
        "fundamental_score": 2,
        "risk_level": "很高",
        "style": "speculative",
        "business_note": "以挖矿和算力资产为主，受 BTC 与电力成本双重影响。",
        "fundamental_note": "盈利弹性大，但波动与周期性同样突出。",
        "watch_items": "BTC、算力利用率、电价、资本开支",
        "news_query": "IREN stock bitcoin miner when:7d",
    },
    {
        "symbol": "NVDA",
        "quote_code": "nvda.us",
        "market": "US",
        "currency": "USD",
        "name": "NVIDIA",
        "name_zh": "英伟达",
        "category": "ai_compute",
        "fundamental_score": 5,
        "risk_level": "中",
        "style": "quality",
        "business_note": "AI 训练与推理的核心平台资产，产业链定价权最强。",
        "fundamental_note": "基本面极强，但估值通常领先反映预期，需要防范高位波动。",
        "watch_items": "数据中心增速、毛利率、AI 资本开支",
        "news_query": "NVDA OR NVIDIA AI stock when:7d",
    },
    {
        "symbol": "AMD",
        "quote_code": "amd.us",
        "market": "US",
        "currency": "USD",
        "name": "AMD",
        "name_zh": "超微公司",
        "category": "ai_compute",
        "fundamental_score": 4,
        "risk_level": "中高",
        "style": "quality",
        "business_note": "CPU、GPU、服务器与 AI 加速卡并进，是第二梯队核心龙头。",
        "fundamental_note": "基本面稳健，估值弹性来自 AI 市占率提升。",
        "watch_items": "MI 系列放量、服务器份额、毛利率",
        "news_query": "AMD stock AI chip when:7d",
    },
    {
        "symbol": "ARM",
        "quote_code": "arm.us",
        "market": "US",
        "currency": "USD",
        "name": "ARM Holdings",
        "name_zh": "ARM",
        "category": "ai_compute",
        "fundamental_score": 3,
        "risk_level": "高",
        "style": "high_growth",
        "business_note": "IP 授权模式轻资产，受移动、PC 与数据中心渗透率影响。",
        "fundamental_note": "业务质量高，但估值偏贵，适合等趋势和估值匹配。",
        "watch_items": "授权收入、数据中心渗透、估值消化",
        "news_query": "ARM Holdings stock AI chip when:7d",
    },
    {
        "symbol": "MU",
        "quote_code": "mu.us",
        "market": "US",
        "currency": "USD",
        "name": "Micron",
        "name_zh": "美光",
        "category": "ai_compute",
        "fundamental_score": 4,
        "risk_level": "中高",
        "style": "cyclical",
        "business_note": "HBM 与存储周期直接相关，是 AI 硬件景气的重要映射。",
        "fundamental_note": "景气向上时弹性大，但需警惕存储价格周期反转。",
        "watch_items": "HBM 供需、存储价格、库存",
        "news_query": "MU OR Micron stock HBM when:7d",
    },
    {
        "symbol": "NBIS",
        "quote_code": "nbis.us",
        "market": "US",
        "currency": "USD",
        "name": "Nebius Group",
        "name_zh": "Nebius",
        "category": "ai_compute",
        "fundamental_score": 2,
        "risk_level": "很高",
        "style": "speculative",
        "business_note": "偏 AI 云和基础设施叙事，成长性高但兑现度仍需观察。",
        "fundamental_note": "处于扩张验证期，适合放在观察仓而非核心仓。",
        "watch_items": "客户增长、云收入、资本开支",
        "news_query": "NBIS OR Nebius stock AI cloud when:7d",
    },
    {
        "symbol": "COHR",
        "quote_code": "cohr.us",
        "market": "US",
        "currency": "USD",
        "name": "Coherent",
        "name_zh": "Coherent",
        "category": "ai_compute",
        "fundamental_score": 3,
        "risk_level": "中高",
        "style": "cyclical",
        "business_note": "光模块和材料设备链条受 AI 网络升级拉动。",
        "fundamental_note": "受订单周期影响较大，趋势确认后更适合跟随。",
        "watch_items": "AI 光通信订单、毛利率、去库存",
        "news_query": "COHR OR Coherent stock optical AI when:7d",
    },
    {
        "symbol": "GLW",
        "quote_code": "glw.us",
        "market": "US",
        "currency": "USD",
        "name": "Corning",
        "name_zh": "康宁",
        "category": "ai_compute",
        "fundamental_score": 3,
        "risk_level": "中",
        "style": "defensive_growth",
        "business_note": "更偏产业配套和材料平台，波动通常低于纯 AI 高弹性股。",
        "fundamental_note": "基本面稳定，但上涨弹性通常弱于前排算力标的。",
        "watch_items": "光通信需求、显示材料、企业订单",
        "news_query": "GLW OR Corning stock optical fiber when:7d",
    },
    {
        "symbol": "ORCL",
        "quote_code": "orcl.us",
        "market": "US",
        "currency": "USD",
        "name": "Oracle",
        "name_zh": "甲骨文",
        "category": "ai_compute",
        "fundamental_score": 4,
        "risk_level": "中",
        "style": "quality",
        "business_note": "数据库与云基建结合，AI 资本开支逻辑明确。",
        "fundamental_note": "现金流和客户基础较稳，是 AI 基建里的中低波动资产。",
        "watch_items": "云订单、资本开支、企业客户扩张",
        "news_query": "ORCL OR Oracle AI cloud stock when:7d",
    },
    {
        "symbol": "META",
        "quote_code": "meta.us",
        "market": "US",
        "currency": "USD",
        "name": "Meta Platforms",
        "name_zh": "Meta",
        "category": "growth_platform",
        "fundamental_score": 5,
        "risk_level": "中",
        "style": "quality",
        "business_note": "广告现金流强，叠加 AI 投放与效率提升，是平台资产核心仓位候选。",
        "fundamental_note": "基本面强、盈利能力高，但估值受市场风格影响。",
        "watch_items": "广告增速、资本开支、AI 变现",
        "news_query": "META stock advertising AI when:7d",
    },
    {
        "symbol": "HIMS",
        "quote_code": "hims.us",
        "market": "US",
        "currency": "USD",
        "name": "Hims & Hers Health",
        "name_zh": "Hims & Hers",
        "category": "healthcare_special",
        "fundamental_score": 3,
        "risk_level": "中高",
        "style": "high_growth",
        "business_note": "医疗服务与订阅模式具成长性，但受监管和执行影响更大。",
        "fundamental_note": "成长逻辑清晰，但波动大，适合趋势和业绩共振时参与。",
        "watch_items": "用户增长、盈利拐点、监管",
        "news_query": "HIMS stock growth health when:7d",
    },
    {
        "symbol": "HOOD",
        "quote_code": "hood.us",
        "market": "US",
        "currency": "USD",
        "name": "Robinhood",
        "name_zh": "Robinhood",
        "category": "growth_platform",
        "fundamental_score": 3,
        "risk_level": "中高",
        "style": "platform",
        "business_note": "零售交易平台，受成交活跃度、加密业务和产品创新驱动。",
        "fundamental_note": "中枢取决于零售交易景气，适合看量价和业务扩张同步。",
        "watch_items": "交易量、用户数、加密业务占比",
        "news_query": "HOOD OR Robinhood stock trading crypto when:7d",
    },
    {
        "symbol": "IBKR",
        "quote_code": "ibkr.us",
        "market": "US",
        "currency": "USD",
        "name": "Interactive Brokers",
        "name_zh": "盈透证券",
        "category": "growth_platform",
        "fundamental_score": 4,
        "risk_level": "中",
        "style": "quality",
        "business_note": "券商平台型资产，盈利质量优于纯交易情绪股。",
        "fundamental_note": "基本面稳健，通常更适合作为防守型金融科技仓位。",
        "watch_items": "客户资产、净利息收入、开户增长",
        "news_query": "IBKR OR Interactive Brokers stock when:7d",
    },
    {
        "symbol": "XPEV",
        "quote_code": "xpev.us",
        "market": "US",
        "currency": "USD",
        "name": "XPeng",
        "name_zh": "小鹏汽车",
        "category": "ev_beta",
        "fundamental_score": 3,
        "risk_level": "高",
        "style": "turnaround",
        "business_note": "产品周期和智能化能力是主线，但行业价格战仍然激烈。",
        "fundamental_note": "改善空间在，但仍属于高波动反转逻辑。",
        "watch_items": "交付量、毛利率、车型周期",
        "news_query": "XPEV OR XPeng stock EV China when:7d",
    },
    {
        "symbol": "NIO",
        "quote_code": "nio.us",
        "market": "US",
        "currency": "USD",
        "name": "NIO",
        "name_zh": "蔚来",
        "category": "ev_beta",
        "fundamental_score": 2,
        "risk_level": "很高",
        "style": "turnaround",
        "business_note": "品牌和换电有特色，但盈利压力与销量兑现仍是核心问题。",
        "fundamental_note": "基本面偏弱，不宜在弱趋势中激进加仓。",
        "watch_items": "交付量、亏损收窄、现金流",
        "news_query": "NIO stock EV China when:7d",
    },
    {
        "symbol": "TSLL",
        "quote_code": "tsll.us",
        "market": "US",
        "currency": "USD",
        "assetclass": "etf",
        "name": "Direxion TSLA Bull 2X",
        "name_zh": "2 倍做多特斯拉 ETF",
        "category": "ev_beta",
        "fundamental_score": 1,
        "risk_level": "很高",
        "style": "leveraged",
        "business_note": "杠杆 ETF，本质是短线交易工具，不适合长期静态持有。",
        "fundamental_note": "不对应企业基本面，只适合波段交易与严格风控。",
        "watch_items": "TSLA 波动率、持有周期、回撤控制",
        "news_query": "TSLL ETF Tesla leveraged when:7d",
    },
    {
        "symbol": "00700.HK",
        "quote_code": "700.hk",
        "market": "HK",
        "currency": "HKD",
        "name": "Tencent",
        "name_zh": "腾讯控股",
        "category": "hk_internet",
        "fundamental_score": 5,
        "risk_level": "中",
        "style": "quality",
        "business_note": "港股互联网核心资产，游戏、广告、支付与生态平台兼具。",
        "fundamental_note": "基本面质量高，是港股科技里更适合长期持有的品种。",
        "watch_items": "游戏审批、广告增速、回购",
        "news_query": "Tencent stock hong kong when:7d",
    },
    {
        "symbol": "03690.HK",
        "quote_code": "3690.hk",
        "market": "HK",
        "currency": "HKD",
        "name": "Meituan-W",
        "name_zh": "美团-W",
        "category": "hk_internet",
        "fundamental_score": 4,
        "risk_level": "中高",
        "style": "platform",
        "business_note": "本地生活龙头，消费修复与竞争格局是两条主线。",
        "fundamental_note": "中长期逻辑仍在，但受消费和补贴竞争扰动较大。",
        "watch_items": "外卖竞争、到店业务、利润率",
        "news_query": "Meituan stock hong kong when:7d",
    },
    {
        "symbol": "09988.HK",
        "quote_code": "9988.hk",
        "market": "HK",
        "currency": "HKD",
        "name": "Alibaba-W",
        "name_zh": "阿里巴巴-W",
        "category": "hk_internet",
        "fundamental_score": 4,
        "risk_level": "中高",
        "style": "turnaround",
        "business_note": "电商与云仍具平台价值，关注组织改革与资本回报。",
        "fundamental_note": "估值不高，但修复持续性取决于业务重回增长。",
        "watch_items": "云业务、回购、电商增长",
        "news_query": "Alibaba stock hong kong cloud when:7d",
    },
    {
        "symbol": "BABA",
        "quote_code": "baba.us",
        "market": "US",
        "currency": "USD",
        "name": "Alibaba ADR",
        "name_zh": "阿里巴巴 ADR",
        "category": "hk_internet",
        "fundamental_score": 4,
        "risk_level": "中高",
        "style": "turnaround",
        "business_note": "美股 ADR 形式持有的阿里，驱动仍是电商、云和资本回报。",
        "fundamental_note": "估值较低但修复依赖业务重回增长，和 9988 本质同源。",
        "watch_items": "云业务、电商增长、回购",
        "news_query": "Alibaba ADR stock when:7d",
    },
    {
        "symbol": "07709.HK",
        "quote_code": "7709.hk",
        "market": "HK",
        "currency": "HKD",
        "name": "CSOP 2x Long Hynix",
        "name_zh": "南方两倍做多海力士",
        "category": "hk_internet",
        "fundamental_score": 1,
        "risk_level": "很高",
        "style": "leveraged",
        "business_note": "韩股海力士两倍杠杆工具，更适合作为短线主题交易仓。",
        "fundamental_note": "不是基本面投资标的，持有周期越长，路径风险越大。",
        "watch_items": "海力士业绩、HBM 价格、持有期限控制",
        "news_query": "7709 HK Hynix leveraged product when:7d",
    },
    {
        "symbol": "45769.HK",
        "quote_code": "45769.hk",
        "market": "HK",
        "currency": "HKD",
        "name": "诺辉健康",
        "name_zh": "诺辉健康",
        "category": "healthcare_special",
        "fundamental_score": 2,
        "risk_level": "高",
        "style": "speculative",
        "business_note": "偏单品与监管主题的医疗成长资产，波动高于主流平台股。",
        "fundamental_note": "需要更严格关注产品兑现和现金流，不适合无纪律重仓。",
        "watch_items": "核心产品销售、监管、融资",
        "news_query": "New Horizon Health stock hong kong when:7d",
    },
]
